export const GET_INTERVIEW = "GET_INTERVIEW";
export const GET_INTERVIEWS = "GET_INTERVIEWS";
export const EDIT_INTERVIEW = "EDIT_INTERVIEW";
export const DELETE_INTERVIEW = "DELETE_INTERVIEW";
export const ADD_INTERVIEW = "ADD_INTERVIEW";
export const UPDATE = "UPDATE";

export const GET_INTERVIEWER = "GET_INTERVIEWER";
export const GET_INTERVIEWERS = "GET_INTERVIEWERS";
export const EDIT_INTERVIEWER = "EDIT_INTERVIEWER";
export const DELETE_INTERVIEWER = "DELETE_INTERVIEWER";
export const ADD_INTERVIEWER = "ADD_INTERVIEWER";


export const GET_INTERVIEWEE = "GET_INTERVIEWEE";
export const GET_INTERVIEWEES = "GET_INTERVIEWEES";
export const EDIT_INTERVIEWEE = "EDIT_INTERVIEWEE";
export const DELETE_INTERVIEWEE = "DELETE_INTERVIEWEE";
export const ADD_INTERVIEWEE = "ADD_INTERVIEWEE";
